services:
   wordpress:
      image: wordpress:latest
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "1"
            memory: "500M"
        placement:
          constraints:
            - node.hostname == node2
      ports:
        - 8085:80

   mysql:
     image: mysql:5.7
     deploy:
       replicas: 1
     environment:
        MYSQL_ROOT_PASSWORD: test123
        MYSQL_DATABASE: wpdb
