services:
   wordpress:
      image: wordpress:latest
      ports:
        - 8080:80
   mysql:
     image: mysql:5.7
     environment:
        MYSQL_ROOT_PASSWORD: test123
        MYSQL_DATABASE: wpdb
     volumes:
      - /root/apple/data/:/var/lib/mysql  ## bind mount volume
      - mydata:/app
volumes:
  mydata:
